SELECT EMP_NAME, AS "이름",SALARY AS "급여" FROM EMPLOYEE;

SELECT DEPT_CODE AS "부서코드",JOB_CODE AS "직무코드" FROM EMPLOYEE;

SELECT EMAIL AS "이메일", PHONE AS "번화번호" FROM EMPLOYEE;

SELECT EMP_ID AS "사원ID", HIRE_DATE AS "입사일" FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", DEPT_CODE AS "부서", SALARY AS "급여" FROM EMPLOYEE;

SELECT DISTINCT DEPT_CODE FROM EMPLOYEE;

SELECT DISTINCT JOB_CODE FROM EMPLOYEE;

SELECT DISTINCT SAL_LEVEL FROM EMPLOYEE;

SELECT DISTINCT MANGER_ID FROM EMPLOYEE;

SELECT DISTINCT EMP_NAME FROM EMPLOYEE;

-- OR

--DEPT_CODE가 D5 이거나 SALARY가 2000000 보다 큰 사원의 이름과 급여 선택
SELECT EMP_NAME,SALARY FROM EMPLOYEE WHERE DEPT_CODE = 'D5' OR SALARY > 2000000;

--DEOT_CODE가 D6이거나 JOB_CODE가 J3인 사원의 이름과 급여 선택
SELECT EMP_NAME,JOB_CODE FROM EMPLOYEE WHERE DEPT_CODE = 'D6' OR JOB_CODE = 'J3';
-- SAL_LEVEL이 S5이거나 BONUS가 0.2 인 사원의 이름과 급여수준 선택
SELECT EMP_NAME,SAL_LEVEL FROM EMPLOYEE WHERE SAL_LEVEL = 'S5' OR BONUS = '0.2';
-- ENT_YN 가 N 이거나 HIRE_DATE 가 2000년 이수인 사원의 이름과 입사일 선택
SELECT EMP_NAME, HIRE_DATE FROM EMPLOYEE WHERE ENT_YN = 'N' OR HIRE_DATE > 
TO_DATE('2000-01-01','YYYY-MM-DD');