/*지금부터 만드는 것은 KH_WORKBOOK 이라는 곳에 만들 테이블 생성*/

CREATE TABLE COMPONY (
COMPONY_ID NUMBER PRIMARY KEY,
COMPONY_NAME VARCHAR2(100) NOT NULL,
COMPONY_ADDRESS VARCHAR2(55),
COMPONY_PHONE VARCHAR2(20)
);

-- COMPONY ALTER 테이블명 COMPANY 변경
ALTER TABLE COMPONY RENAME TO COMPANY;
SELECT * FROM COMPANY;

-- COMPANY 시퀀스 생성
-- 시퀀스명 COMPANY_SEQ 시작값 1 증가값 1 NOCACHE NOCYCLE
-- 방법1
CREATE SEQUENCE COMPANY_SEQ;
-- 방법2
CREATE SEQUENCE COMPANY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE
;

-- INSERT COMPANY 회사 추가
INSERT INTO COMPANY
VALUES(company_seq.nextval,'햇에제과','서울시 강남구','02-1234-5678');
INSERT INTO COMPANY
VALUES(company_seq.nextval,'롯에제과','서울시 중구','02-2345-6789');
INSERT INTO COMPANY
VALUES(company_seq.nextval,'올이온','서울시 용산구','02-3456-7890');
-- NEXTVAL 이용해서 회사 추가
-- '롯에제과','서울시 중구','02-2345-6789'
-- '올이온','서울시 용산구','02-3456-7890'
SELECT * FROM COMPANY;

-- SNACKS 테이블 생성
CREATE TABLE SNACKS (
SNACK_ID NUMBER(10,0) PRIMARY KEY,
SNACK_NAME VARCHAR2(100) NOT NULL,
PRICE NUMBER(10,2) NOT NULL,
COMPONY_ID NUMBER(10,0),
CONSTRAINT COMPANY FOREIGN KEY (COMPONY_ID)
REFERENCES COMPANY (COMPONY_ID)
);

CREATE SEQUENCE SNACKS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO SNACKS
VALUES (snacks_seq.nextval,'오에스',1500,1);
INSERT INTO SNACKS
VALUES (snacks_seq.nextval,'칸조',1220,1);
INSERT INTO SNACKS
VALUES (snacks_seq.nextval,'배배로',1100,2);
INSERT INTO SNACKS
VALUES (snacks_seq.nextval,'조고파이',2000,2);

SELECT * FROM SNACKS;

-- 가격 1500 이상인 과자 조회
SELECT * FROM SNACKS WHERE PRICE >= 1500;
-- 서울시 강남구 에 위치한 회사 조회

-- 회사 ID가 1인 과자 조회
SELECT * FROM SNACKS WHERE COMPANY_ID = 1;
-- 회사 ID 가 1이고 그 회사에 과자들 조회 (JOIN)
SELECT C.COMPANY_NAME,S.SNACK_NAME,S.PRICE
FROM COMPANY C
JOIN SNACKS S ON C.COMPANY_ID = SC.COMPANY_ID
WHERE C.COMPANY_ID = 1;