SELECT E.EMP_NAME,E.EMP_NO,D.DEPT_TITLE,J.JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.EMP_NO LIKE '7%'
AND SUBSTR(E.EMP_NO,8,1)IN('2','4') -- 1900년대는 2 2000년대는 4
AND E.EMP_NAME LIKE '전%';
-- 전지연	770808-2665412	인사관리부	대리

SELECT E.EMP_ID,E.EMP_NAME,J.JOB_NAME
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.EMP_NAME LIKE '%형%';

SELECT E.EMP_NAME,J.JOB_NAME,E.DEPT_CODE,D.DEPT_TITLE
FROM EMPLOYEE E
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.DEPT_CODE IN ('D5','D6');

-- SELECT * FROM DEPARTMENT 실행
-- D5 해외영업 1부
-- D6 해외영업 2부


SELECT E.EMP_NAME,E.BONUS,D.DEPT_TITLE,L.LOCAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DEPT_ID = E.DEPT_CODE
JOIN LOCATION L ON L.LOCAL_CODE = D.LOCATION_ID
WHERE E.BONUS IS NOT NULL;

SELECT E.EMP_NAME,J.JOB_NAME,D.DEPT_TITLE,L.LOCAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DEPT_ID = E.DEPT_CODE
JOIN LOCATION L ON L.LOCAL_CODE = D.LOCATION_ID
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE;

SELECT E.EMP_NAME,J.JOB_NAME,E.SALARY,(E.SALARY + NVL(E.BONUS,'0')) * 12 AS "연봉"
FROM EMPLOYEE E
JOIN SAL_GRADE S ON E.SAL_LEVEL = S.SAL_LEVEL
-- SAL_GRADE 테이블과 EMPLOYEE 테이블을 조인하기 위해 서로 값이 같은 컬럼을 연결
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
-- JOB 테이블과 EMPLOYEE 테이블 조인하기 위해 서로 값이 같은 컬럼을 연결
WHERE E.SALARY > s.min_sal;
-- 직원의 급여가 최소 급여보다 큰 직원들만 선택할 수 있도록 조건 설정

SELECT E.EMP_NAME,D.DEPT_TITLE,L.LOCAL_NAME,N.NATIONAL_NAME
FROM EMPLOYEE E
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN NATIONAL N ON l.national_code = n.national_code
WHERE n.national_code IN ('KO','JP');

SELECT E1.EMP_NAME,E1.DEPT_CODE,E2.EMP_NAME
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.DEPT_CODE = E2.DEPT_CODE
AND E1.EMP_ID != E2.EMP_ID; 
-- 내 부서에서 나와 같이 근무하는 사람들을 봐야하기 때문에 내 코드는 보여주지 않겠다.

--E1.DEPT_CODE = E2.DEPT_CODE 같은 부서에 있으면서
-- E1.EMP_ID != E2.EMP_ID; 서로 다른 직원일 경우에만 조회

SELECT E.EMP_NAME,J.JOB_NAME,E.SALARY
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.BONUS IS NULL
AND E.JOB_CODE IN ('J4','J7');
