-- MENU 테이블
-- 메뉴이름 맨 앞에 카 가 들어간 메뉴 출력
SELECT * FROM MENU WHERE MENU_NAME LIKE '카%';
-- MENU_PRICE 3500 인 메뉴들 출력
SELECT * FROM MENU WHERE MENU_PRICE = '3500';
-- 키오스크에서 1을 눌렀을 때 나올 메뉴 출력
SELECT * FROM MENU WHERE MENU_ID = '1';
-- 특정 단어가 포함된 메뉴 설명 조회 카라멜
SELECT MENU_NAME,MENU_DESC,MENU_PRICE FROM MENU WHERE MENU_DESC LIKE '%카라멜%';
-- 가격이 낮은 순으로 메뉴 조회
SELECT MENU_NAME,MENU_DESC,MENU_PRICE FROM MENU ORDER BY MENU_PRICE ASC;

-- 직급 코드가 J5인 사원의 수를 조회
-- J5 몇명?
SELECT COUNT(*) AS "J5 COUNT"
FROM EMPLOYEE
WHERE JOB_CODE = 'J5';

-- 사원의 이름과 이메일을 결합해서 조회
SELECT EMP_NAME||'('||EMAIL||')'
FROM EMPLOYEE;

-- 사원의 이름과 전화번호를 - 사용해서 조회
SELECT EMP_NAME ||'-'||  PHONE 
FROM EMPLOYEE;
-- 사원의 사번과 부서코드를 - 사용해서 조회
SELECT EMP_ID || '-' || DEPT_CODE 
FROM EMPLOYEE;
-- 사원의 이름과 급여를 이름 : 급여 형식으로 조회 AS 이름 : 급여
SELECT EMP_NAME || ':' || SALARY AS "이름 : 급여" FROM EMPLOYEE;
-- 사원의 이름 - 연봉 형식으로 조회
SELECT EMP_NAME || '-' || SALARY * 12 AS "이름 - 연봉" FROM EMPLOYEE;


/****** WHERE 절 사용 논리 연산자 NOT ******/
SELECT EMP_NAME,DEPT_CODE FROM EMPLOYEE WHERE DEPT_CODE != 'D5';

SELECT EMP_NAME,SALARY FROM EMPLOYEE WHERE SALARY < '3000000';

SELECT EMP_NAME,JOB_CODE FROM EMPLOYEE WHERE JOB_CODE != 'J3';

SELECT EMP_NAME,BONUS FROM EMPLOYEE WHERE BONUS != '0.1';
-- 숫자의 경우 " ' 사용하지 않아도 사용이 가능
SELECT EMP_NAME,MANAGER_ID FROM EMPLOYEE WHERE MANAGER_ID != '200';
/****** NULL 비교하기 IS NULL ******/
SELECT EMP_NAME,EMAIL FROM EMPLOYEE WHERE EMAIL IS NULL;
-- 이메일 칸에 이메일이 없는 사람들 조회
--> 사람조회가 안된다면 모두 이메일을 작성해준 것
SELECT EMP_NAME,PHONE FROM EMPLOYEE WHERE PHONE IS NULL;

SELECT EMP_NAME,BONUS FROM EMPLOYEE WHERE BONUS IS NULL;

SELECT EMP_NAME,MANAGER_ID FROM EMPLOYEE WHERE MANAGER_ID IS NULL;

SELECT EMP_NAME,ENT_DATE FROM EMPLOYEE WHERE ENT_DATE IS NULL;
/****** NULL 비교하기 IS NOT NULL ******/
SELECT EMP_NAME,EMAIL FROM EMPLOYEE WHERE EMAIL IS NOT NULL;

SELECT EMP_NAME,PHONE FROM EMPLOYEE WHERE PHONE IS NOT NULL;

SELECT EMP_NAME,BONUS FROM EMPLOYEE WHERE BONUS IS NOT NULL;

SELECT EMP_NAME,MANAGER_ID FROM EMPLOYEE WHERE MANAGER_ID IS NOT NULL;

SELECT EMP_NAME,ENT_DATE FROM EMPLOYEE WHERE ENT_DATE IS NOT NULL;
/****** BETWEEN AND 연산자 사용 ******/
SELECT EMP_NAME,SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 2000000 AND 3000000;

SELECT EMP_NAME,HIRE_DATE FROM EMPLOYEE WHERE HIRE_DATE 
BETWEEN TO_DATE('2000-01-01','YYYY-MM-DD') AND TO_DATE ('2010-12-31','YYYY-MM-DD');

SELECT EMP_NAME,EMP_ID FROM EMPLOYEE WHERE EMP_ID BETWEEN '210' AND '220';

SELECT EMP_NAME,BONUS FROM EMPLYOEE WHERE BONUS BETWEEN 0.1 AND 0.3;

SELECT EMP_NAME,SAL_LEVEL FROM EMPLOYEE WHERE SAL_LEVEL BETWEEN 'S3' AND 'S5';

/****** NOT BETWEEN 연산자 사용 ******/
SELECT EMP_NAME,SALARY FROM EMPLOYEE WHERE SALARY NOT BETWEEN 2000000 AND 3000000;

SELECT EMP_NAME,HIRE_DATE FROM EMPLOYEE WHERE HIRE_DATE 
NOT BETWEEN TO_DATE('2000-01-01','YYYY-MM-DD') AND TO_DATE('2010-12-31','YYYY-MM-DD');

SELECT EMP_NAME,EMP_ID FROM EMPLOYEE WHERE EMP_ID NOT BETWEEN '210' AND '220';

SELECT EMP_NAME,BONUS FROM EMPLOYEE WHERE BONUS NOT BETWEEN 0.1 AND 0.3;

SELECT EMP_NAME,SAL_LEVEL FROM EMPLOYEE WHERE SAL_LEVEL NOT BETWEEN 'S3' AND 'S5';