--- ORDER BY ---
SELECT * FROM DEPARTMENT
ORDER BY DEPT_TITLE; -- ASC 오름차순

SELECT * FROM EMPLOYEE
ORDER BY SALARY DESC;

SELECT EMP_NAME,HIRE_DATE FROM EMPLOYEE
ORDER BY HIRE_DATE;

SELECT LOCAL_NAME,NATIONAL_CODE FROM LOCATION
ORDER BY NATIONAL_CODE;

SELECT EMP_ID,EMP_NAME FROM EMPLOYEE
ORDER BY EMP_NAME;

-- FROM 찾을테이블 위치 선정 -> SELECT 조회 -> ORDER BY 정렬

--- HAVING -> GROUP BY 사용항다는 의미 ---
SELECT DEPT_CODE, AVG(SALARY) AS "평균급여"
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING AVG(SALARY) > 3000000;

-- WHERE : 조건에 해당하는 사람들을 검색한다음 조건에 부합하는 것처럼 보임
-- GROUP HAVING : 모든 ~ 사람들을 조회하고 조건에 맞는 부서만 선별

SELECT JOB_CODE, COUNT(*) AS "직원수"
FROM EMPLOYEE
GROUP BY JOB_CODE
HAVING COUNT(*) >= 3;

SELECT DEPT_CODE,SUM(SALARY) AS "급여합계"
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING SUM(SALARY) >= 10000000;

SELECT SAL_LEVEL,MAX(SALARY) AS "최대급여"
FROM EMPLOYEE
GROUP BY SAL_LEVEL
HAVING MAX(SALARY) < 5000000;

SELECT DEPT_CODE,MIN(SALARY) AS "최소급여"
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING MIN(SALARY) >= 2000000;

-- FROM 찾을테이블위치 선정 -> GROUP BY 묶을그룹선정 -> HAVING 조건 설정 -> SELECT 그룹조건에 맞는 내용 조회

--- GROUP BY ---
SELECT DEPT_CODE,COUNT(*) AS "직원수"
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT JOB_CODE,FLOOR(AVG(SALARY)) AS "평균급여"
FROM EMPLOYEE
GROUP BY JOB_CODE;

--> AVG나 SUM으로 수의 합에 대한 결과를 구할 때
---> 정수 밑에 있는 소수점을 제거하길 원한다면
----> CEIL, FLOOR, ROUND 설정

--- WHERE ---
SELECT EMP_NAME,SALARY AS "급여" FROM EMPLOYEE
WHERE SALARY >=  3000000;

SELECT * FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';